name: Build v8
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./build.sh
      - name: release
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: release
          folder: v8/build
