name: Build the latest stable V8
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
  pull_request:
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest stable V8 commit
        run: |
          export PATH=$(pwd)/depot_tools:$PATH
          export V8_MINOR_VERSION=$(curl -sSL 'https://omahaproxy.appspot.com/all.json?os=linux&channel=stable' | jq -r '.[0].versions[0].v8_version | match("\\d+\\.\\d+").string')
          export COMMIT=$(git ls-remote -q https://chromium.googlesource.com/v8/v8.git refs/branch-heads/$V8_MINOR_VERSION | awk '{ print $1 }')
          echo $COMMIT | tee .commit
      - name: Upload .commit
        uses: actions/upload-artifact@v2
        with:
          name: commit
          path: .commit
          retention-days: 1
  include:
    runs-on: ubuntu-latest
    needs: commit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Download .commit
        uses: actions/download-artifact@v2
        with:
          name: commit
      - name: Fetch V8
        run: |
          COMMIT=`cat .commit` ./fetch.sh
          mkdir artifact && mv v8/v8/include artifact
      - name: Upload include files
        uses: actions/upload-artifact@v2
        with:
          name: include
          path: artifact
          retention-days: 1
  build:
    needs: commit
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        include:
          - platform: ubuntu-latest
            dir: linux
          - platform: macos-latest
            dir: macos
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Download commit
        uses: actions/download-artifact@v2
        with:
          name: commit
      - name: Fetch V8
        run: |
          COMMIT=`cat .commit` ./fetch.sh
      - name: Install build deps
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt update && sudo apt remove php7.4-common && sudo apt autoremove && ./v8/v8/build/install-build-deps.sh
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.platform }}
      - name: Build V8
        run: ./build.sh
      - name: Rename static library
        run: mkdir -p artifact/${{ matrix.dir }} && mv v8/v8/out.gn/release/obj/libv8_monolith.a artifact/${{ matrix.dir }}/libv8.a
      - name: Upload static library
        uses: "actions/upload-artifact@v2"
        with:
          name: libv8-${{ matrix.platform }}
          path: artifact
          retention-days: 1
  release:
    runs-on: ubuntu-latest
    needs:
      - include
      - build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download .commit
        uses: actions/download-artifact@v2
        with:
          name: commit
          path: v8/out/
      - name: Download include
        uses: actions/download-artifact@v2
        with:
          name: include
          path: v8/out/
      - name: Download Linux build
        uses: actions/download-artifact@v2
        with:
          name: libv8-ubuntu-latest
          path: v8/out/
      - name: Download macOS build
        uses: actions/download-artifact@v2
        with:
          name: libv8-macos-latest
          path: v8/out/
      - name: Prepare
        id: prepare
        run: |
          VERSION=$(git ls-remote -q --tags https://chromium.googlesource.com/v8/v8.git | grep $(cat v8/out/.commit) | awk '{ print $2 }' | awk -F/ '{ print $3 }')
          echo $VERSION
          echo "::set-output name=VERSION::$VERSION"
          if git rev-parse $VERSION > /dev/null 2>&1; then
            echo tag $VERSION already exists
            echo ::set-output name=SKIP_RELEASE::true
          else
            echo ::set-output name=SKIP_RELEASE::false
            cd v8/out
            zip -r linux.zip include linux
            zip -r macos.zip include macos
          fi
      - name: Release
        if: ${{ github.event.schedule && !fromJSON(steps.prepare.outputs.SKIP_RELEASE) }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.prepare.outputs.VERSION }}
          files: |
            v8/out/linux.zip
            v8/out/macos.zip
