name: Build the latest stable V8
on:
  push:
    branches:
      - main
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest stable V8 commit
        run: |
          export PATH=$(pwd)/depot_tools:$PATH
          export V8_MINOR_VERSION=$(curl -sSL 'https://omahaproxy.appspot.com/all.json?os=linux&channel=stable' | jq -r '.[0].versions[0].v8_version | match("\\d+\\.\\d+").string')
          export COMMIT=$(git ls-remote -q https://chromium.googlesource.com/v8/v8.git refs/branch-heads/$V8_MINOR_VERSION | awk '{ print $1 }')
          echo $COMMIT | tee .commit
      - name: Upload .commit
        uses: actions/upload-artifact@v2
        with:
          name: commit
          path: .commit
          retention-days: 1
  include:
    runs-on: ubuntu-latest
    needs: commit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Get commit
        uses: actions/download-artifact@v2
        with:
          name: commit
      - name: Fetch V8
        run: |
          COMMIT=`cat .commit` ./fetch.sh
          mkdir artifact && mv v8/v8/include artifact
      - name: Upload include files
        uses: actions/upload-artifact@v2
        with:
          name: include
          path: artifact
          retention-days: 1
  build:
    needs: commit
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        include:
          - platform: ubuntu-latest
            dir: linux
          - platform: macos-latest
            dir: macos
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Get commit
        uses: actions/download-artifact@v2
        with:
          name: commit
      - name: Fetch V8
        run: |
          COMMIT=`cat .commit` ./fetch.sh
      - name: Install build deps
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt update && sudo apt remove php7.4-common && sudo apt autoremove && ./v8/v8/build/install-build-deps.sh
      - name: Build V8
        run: ./build.sh
      - name: Rename static library
        run: mkdir -p artifact/${{ matrix.dir }} && mv v8/v8/out.gn/release/obj/libv8_monolith.a artifact/${{ matrix.dir }}/libv8.a
      - name: Upload static library
        uses: "actions/upload-artifact@v2"
        with:
          name: libv8-${{ matrix.platform }}
          path: artifact
          retention-days: 1
  release:
    runs-on: ubuntu-latest
    needs:
      - include
      - build
    steps:
      - name: Download .commit
        uses: actions/download-artifact@v2
        with:
          name: commit
      - name: Download include
        uses: actions/download-artifact@v2
        with:
          name: include
      - name: Download Linux build
        uses: actions/download-artifact@v2
        with:
          name: libv8-ubuntu-latest
      - name: Download macOS build
        uses: actions/download-artifact@v2
        with:
          name: libv8-macos-latest
      - name: Test output
        uses: "actions/upload-artifact@v2"
        with:
          name: output
          path: .
          retention-days: 1
      # - name: Release
      #   uses: JamesIves/github-pages-deploy-action@4.1.4
      #   with:
      #     branch: release
      #     folder: v8/build
